2022-05-14 17:42:07 M scripts/clean/cl M scripts/find/ffind M scripts/git/git-pp M scripts/git/git-up M scripts/ip/ip M scripts/ip/ip-lo M scripts/kill/k M scripts/kill/k-pd M scripts/proxy/proxy M scripts/start/s M scripts/start/s-vpn

diff --git a/scripts/ip/ip b/scripts/ip/ip
--- a/scripts/ip/ip
+++ b/scripts/ip/ip
@@ -2,14 +2,11 @@
 
 if [[ $# > 0 ]]
 then
-    command -v ip-$1 > /dev/null
-    if [[ $? == 0 ]]
-    then
-        ip-$@
-    else
-        echo "ip-$1 not found"
+    command -v ip-$1 &> /dev/null || {
+        echo "ip-$1: command not found"
         exit 1
-    fi
+    }
+    ip-$@
 else
     ip lo
 fi
